"""
Seed the exercise library with ~50 common exercises + aliases for FitNotes names.
"""
import json

EXERCISES = [
    # CHEST
    {
        "name": "Bench Press",
        "aliases": ["Flat Bench Press", "Barbell Bench Press"],
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Triceps", "Front Delts"],
        "equipment": "barbell",
        "movement_pattern": "push",
        "is_compound": True,
    },
    {
        "name": "Incline Dumbbell Press",
        "aliases": ["Incline DB Press"],
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Front Delts", "Triceps"],
        "equipment": "dumbbell",
        "movement_pattern": "push",
        "is_compound": True,
    },
    {
        "name": "Dips (Weighted)",
        "aliases": ["Chest Dips", "Weighted Dips", "Paused Strict Dips"],
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Triceps", "Front Delts"],
        "equipment": "bodyweight",
        "movement_pattern": "push",
        "is_compound": True,
    },
    {
        "name": "Cable Fly",
        "aliases": ["Cable Crossover", "Crossover Unilateral", "Incline Cable Fly"],
        "primary_muscles": ["Chest"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Chest Fly",
        "aliases": ["Dumbbell Fly", "Floor Dumbbell Uni Press"],
        "primary_muscles": ["Chest"],
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Close-Grip Bench Press",
        "aliases": ["Close-grip Bench Press", "Smith CGBP"],
        "primary_muscles": ["Triceps"],
        "secondary_muscles": ["Chest"],
        "equipment": "barbell",
        "movement_pattern": "push",
        "is_compound": True,
    },
    {
        "name": "Chest Press Machine",
        "aliases": ["Chest Press Machine - Apt", "Cross-body Machine Chest Press"],
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Triceps"],
        "equipment": "machine",
        "movement_pattern": "push",
        "is_compound": True,
    },
    # BACK / LATS
    {
        "name": "Pull-up",
        "aliases": ["Pull ups to Chest", "Pullup", "Pull-ups Pronated"],
        "primary_muscles": ["Lats"],
        "secondary_muscles": ["Upper Back", "Biceps"],
        "equipment": "bodyweight",
        "movement_pattern": "pull",
        "is_compound": True,
    },
    {
        "name": "Pull-up (Neutral Grip)",
        "aliases": ["Pull-up Neutral Grip", "Gironda Sternum Neutral Chins"],
        "primary_muscles": ["Lats"],
        "secondary_muscles": ["Upper Back", "Biceps"],
        "equipment": "bodyweight",
        "movement_pattern": "pull",
        "is_compound": True,
    },
    {
        "name": "Chin-up",
        "aliases": ["Chinups", "Underhand Chins"],
        "primary_muscles": ["Lats"],
        "secondary_muscles": ["Biceps"],
        "equipment": "bodyweight",
        "movement_pattern": "pull",
        "is_compound": True,
    },
    {
        "name": "Lat Pulldown",
        "aliases": ["Lat Pull-down", "Pulldown", "45 Degree Single Lat Pulldown", "Single Lat Pulldown"],
        "primary_muscles": ["Lats"],
        "secondary_muscles": ["Upper Back", "Biceps"],
        "equipment": "cable",
        "movement_pattern": "pull",
        "is_compound": True,
    },
    {
        "name": "Lat Pull-in",
        "aliases": ["Rope Pullover", "Pullover - Individual Handles", "Dumbbell Pullover", "Incline Dumbbell Pullover"],
        "primary_muscles": ["Lats"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_pattern": "pull",
        "is_compound": False,
    },
    {
        "name": "Seated Row",
        "aliases": ["Seated Rows - Close Grip", "Seated Rows - Swissies", "Seated Rows - Wide", "Seated Unilateral Rows", "Shake Wide Seated Rows"],
        "primary_muscles": ["Upper Back"],
        "secondary_muscles": ["Lats", "Biceps"],
        "equipment": "cable",
        "movement_pattern": "pull",
        "is_compound": True,
    },
    {
        "name": "Chest Supported Row",
        "aliases": ["Chest Supported Rows"],
        "primary_muscles": ["Upper Back"],
        "secondary_muscles": ["Biceps"],
        "equipment": "dumbbell",
        "movement_pattern": "pull",
        "is_compound": True,
    },
    {
        "name": "Dumbbell Row",
        "aliases": ["One-arm Row", "One-Arm Dumbbell Row"],
        "primary_muscles": ["Lats"],
        "secondary_muscles": ["Upper Back", "Biceps"],
        "equipment": "dumbbell",
        "movement_pattern": "pull",
        "is_compound": True,
    },
    {
        "name": "Face Pull",
        "aliases": ["Shake Face Pulls", "Unilateral Rope Face Pulls"],
        "primary_muscles": ["Rear Delts"],
        "secondary_muscles": ["Upper Back"],
        "equipment": "cable",
        "movement_pattern": "pull",
        "is_compound": False,
    },
    {
        "name": "Seated Row Shrugback",
        "aliases": ["Seated Row Shrugback", "Dual Cable Shrugback"],
        "primary_muscles": ["Upper Back"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_pattern": "pull",
        "is_compound": False,
    },
    # SHOULDERS
    {
        "name": "Overhead Press",
        "aliases": ["Seated Overhead DB Press", "Unilateral Standing Dumbbell Press", "High Incline Shoulder Press", "High Incline Smith Shoulder Press", "Dante Shoulder Press"],
        "primary_muscles": ["Front Delts"],
        "secondary_muscles": ["Middle Delts", "Triceps"],
        "equipment": "dumbbell",
        "movement_pattern": "push",
        "is_compound": True,
    },
    {
        "name": "Lateral Raise",
        "aliases": ["Cable Laterals Behind", "Cable Laterals with D Handle", "Egyptian Laterals", "Lean-away Dumbbell Lateral Raise", "Lu Raises", "Incline Lateral Raise"],
        "primary_muscles": ["Middle Delts"],
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Rear Delt Fly",
        "aliases": ["Dumbbell Rear-delt Flys", "Unilateral Rear-delt Flys"],
        "primary_muscles": ["Rear Delts"],
        "secondary_muscles": ["Upper Back"],
        "equipment": "dumbbell",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Front Raise",
        "aliases": ["Incline Front Raise", "Plate Raises"],
        "primary_muscles": ["Front Delts"],
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Upright Row",
        "aliases": ["Rope Upright Row"],
        "primary_muscles": ["Middle Delts"],
        "secondary_muscles": ["Upper Back"],
        "equipment": "cable",
        "movement_pattern": "pull",
        "is_compound": False,
    },
    {
        "name": "Shrugs",
        "aliases": ["Dumbbell Shrugs", "Seated Dumbbell Shrugs", "Unilateral Cable Shrugs"],
        "primary_muscles": ["Upper Back"],
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Cable Trap Raise",
        "aliases": ["Cable trap raise"],
        "primary_muscles": ["Upper Back"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    # BICEPS
    {
        "name": "Cable Curl",
        "aliases": ["Unilateral Cable Curls Behind", "Cable Curls"],
        "primary_muscles": ["Biceps"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Incline Dumbbell Curl",
        "aliases": ["Incline Dumbbell Curls", "Incline Hammer Curls"],
        "primary_muscles": ["Biceps"],
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "EZ Bar Curl",
        "aliases": ["EZ Curls", "Alternating Bicep Curls"],
        "primary_muscles": ["Biceps"],
        "secondary_muscles": [],
        "equipment": "barbell",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Concentration Curl",
        "aliases": ["Concentration Curls"],
        "primary_muscles": ["Biceps"],
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Preacher Curl",
        "aliases": ["Preacher Unilateral Curls", "Hammer Preacher DB curls"],
        "primary_muscles": ["Biceps"],
        "secondary_muscles": [],
        "equipment": "machine",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Hammer Curl",
        "aliases": ["Cable Rope Hammer Curls", "Pinwheel Curls"],
        "primary_muscles": ["Biceps"],
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Reverse Curl",
        "aliases": ["Reverse Cable Curls"],
        "primary_muscles": ["Biceps"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    # TRICEPS
    {
        "name": "Tricep Pushdown",
        "aliases": ["Pushdown", "Rope Pushdown", "Single Tricep Pushdown", "Tricep Shake Pushdown"],
        "primary_muscles": ["Triceps"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Overhead Tricep Extension",
        "aliases": ["Overhead Cable Tricep Extension", "Unilateral Overhead Tricep Cable Extension", "Overhead Tricep Extension", "Uni rope tricep extension from behind", "Unilateral Tricep Ext Behind - Shake", "Tricep Extension from Behind"],
        "primary_muscles": ["Triceps"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Cable Kickback",
        "aliases": ["Cable Kickback"],
        "primary_muscles": ["Triceps"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    # LEGS
    {
        "name": "Squat",
        "aliases": ["Barbell Squat", "Squat Press"],
        "primary_muscles": ["Quadriceps"],
        "secondary_muscles": ["Glutes", "Hamstrings"],
        "equipment": "barbell",
        "movement_pattern": "squat",
        "is_compound": True,
    },
    {
        "name": "Bulgarian Split Squat",
        "aliases": ["Bulgarian Split Squat", "Sissy Squats"],
        "primary_muscles": ["Quadriceps"],
        "secondary_muscles": ["Glutes"],
        "equipment": "dumbbell",
        "movement_pattern": "squat",
        "is_compound": True,
    },
    {
        "name": "Leg Extension",
        "aliases": ["Leg Extenstion - Apt Gym", "Leg Extension - Apt Gym"],
        "primary_muscles": ["Quadriceps"],
        "secondary_muscles": [],
        "equipment": "machine",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Leg Curl (Seated/Lying)",
        "aliases": ["Leg Curls - Apt gym", "Unilateral Leg Curls"],
        "primary_muscles": ["Hamstrings"],
        "secondary_muscles": [],
        "equipment": "machine",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Romanian Deadlift",
        "aliases": ["Dumbbell Romanian Deadlift"],
        "primary_muscles": ["Hamstrings"],
        "secondary_muscles": ["Glutes", "Lower Back / Spinal Erectors"],
        "equipment": "dumbbell",
        "movement_pattern": "hinge",
        "is_compound": True,
    },
    {
        "name": "Cable Pull Through",
        "aliases": ["Cable Pull Through"],
        "primary_muscles": ["Glutes"],
        "secondary_muscles": ["Hamstrings"],
        "equipment": "cable",
        "movement_pattern": "hinge",
        "is_compound": True,
    },
    {
        "name": "Skiers",
        "aliases": ["Skiers"],
        "primary_muscles": ["Glutes"],
        "secondary_muscles": ["Hamstrings"],
        "equipment": "cable",
        "movement_pattern": "hinge",
        "is_compound": False,
    },
    # CALVES
    {
        "name": "Calf Raise",
        "aliases": ["Standing Calf Raise", "Calf Press", "Unilateral Calf Raise", "Unilateral Calf Press", "Seated DB Calf Raise", "Seated Myo Calf Raises"],
        "primary_muscles": ["Calves"],
        "secondary_muscles": [],
        "equipment": "machine",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Seated Calf Raise",
        "aliases": ["Seated Calf Raise"],
        "primary_muscles": ["Calves"],
        "secondary_muscles": [],
        "equipment": "machine",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Tibialis Raise",
        "aliases": ["Tibialis Raise - Cable", "Standing Tibialis Raise"],
        "primary_muscles": ["Calves"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    # CORE / ABS
    {
        "name": "Ab Wheel Rollout",
        "aliases": ["Ab Wheel Rollout"],
        "primary_muscles": ["Abs/Core"],
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Cable Crunch",
        "aliases": ["Cable Crunches"],
        "primary_muscles": ["Abs/Core"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Hanging Leg Raise",
        "aliases": ["Hanging Leg Raise", "Captain's Chair Leg Raises", "Hanging Oblique Raises"],
        "primary_muscles": ["Abs/Core"],
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Jackknife",
        "aliases": ["Jackknives"],
        "primary_muscles": ["Abs/Core"],
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Crunch",
        "aliases": ["Floor Crunches", "Swiss Ball Crunches", "Weighted Crunch"],
        "primary_muscles": ["Abs/Core"],
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Pallof Press",
        "aliases": ["Pallof Press"],
        "primary_muscles": ["Abs/Core"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    {
        "name": "Wood Chopper",
        "aliases": ["Wood Chopper"],
        "primary_muscles": ["Abs/Core"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_pattern": "isolation",
        "is_compound": False,
    },
    # BACK EXTENSION / LOWER BACK
    {
        "name": "Back Extension",
        "aliases": ["Back Extension"],
        "primary_muscles": ["Lower Back / Spinal Erectors"],
        "secondary_muscles": ["Glutes"],
        "equipment": "machine",
        "movement_pattern": "hinge",
        "is_compound": False,
    },
    # FOREARMS / WRISTS
    {
        "name": "Wrist Curl",
        "aliases": ["Dumbbell Wrist Curls", "Cable wrist curls from above - uni", "Cable wrist extension from above - uni", "Wrist Curls - Behind the Back", "Standing Dumbbell Forearm Curls"],
        "primary_muscles": ["Abs/Core"],  # using as misc; normally "Forearms" but not in taxonomy
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "movement_pattern": "isolation",
        "is_compound": False,
        "notes": "Forearm exercise",
    },
]


def get_seed_data():
    return EXERCISES
