"""initial schema

Revision ID: 0588c6160f1b
Revises: 
Create Date: 2026-05-03 10:04:20.541528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0588c6160f1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dexa_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_date', sa.Date(), nullable=False),
    sa.Column('total_lbs', sa.Float(), nullable=True),
    sa.Column('lean_lbs', sa.Float(), nullable=True),
    sa.Column('fat_lbs', sa.Float(), nullable=True),
    sa.Column('bf_pct', sa.Float(), nullable=True),
    sa.Column('arms_lbs', sa.Float(), nullable=True),
    sa.Column('legs_lbs', sa.Float(), nullable=True),
    sa.Column('trunk_lbs', sa.Float(), nullable=True),
    sa.Column('vat_kg', sa.Float(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_date')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aliases', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_muscles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secondary_muscles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('equipment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('movement_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_compound', sa.Boolean(), nullable=False),
    sa.Column('target_reps_low', sa.Integer(), nullable=True),
    sa.Column('target_reps_high', sa.Integer(), nullable=True),
    sa.Column('progression_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_name'), ['name'], unique=True)

    op.create_table('microcycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('body_weight_lbs', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emphasis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('body_weight_lbs', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_date'), ['date'], unique=False)

    op.create_table('whoop_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('recovery_score', sa.Float(), nullable=True),
    sa.Column('hrv_ms', sa.Float(), nullable=True),
    sa.Column('rhr_bpm', sa.Float(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('strain', sa.Float(), nullable=True),
    sa.Column('zone4_5_minutes', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('session_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_order', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_exercises_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_exercises_session_id'), ['session_id'], unique=False)

    op.create_table('pr_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('session_exercise_id', sa.Integer(), nullable=False),
    sa.Column('pr_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pr_value', sa.Float(), nullable=False),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['session_exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pr_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_records_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pr_records_session_exercise_id'), ['session_exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pr_records_session_id'), ['session_id'], unique=False)

    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['session_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sets_session_exercise_id'), ['session_exercise_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sets_session_exercise_id'))

    op.drop_table('sets')
    with op.batch_alter_table('pr_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_records_session_id'))
        batch_op.drop_index(batch_op.f('ix_pr_records_session_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_pr_records_exercise_id'))

    op.drop_table('pr_records')
    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_exercises_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_exercises_exercise_id'))

    op.drop_table('session_exercises')
    op.drop_table('whoop_days')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_date'))

    op.drop_table('sessions')
    op.drop_table('nutrition_days')
    op.drop_table('microcycles')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_name'))

    op.drop_table('exercises')
    op.drop_table('dexa_scans')
    # ### end Alembic commands ###
